экспорт графики
htmlacademy-adaptive/1996827-mishka-26 pull request #2
Opened 2022-07-29 00:11 UTC by ustyugovki

module2-task1

2022-07-31 16:22 UTC, summertime-fms requested changes

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +<html class="page" lang="ru">
В демках это есть, но на деле этот класс тут скорее всего не понадобится, т.к. html вряд ли  переиспользуемый блок

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +      <div class="page__container">
Тут лучше сделать container/wrapper отдельным блоком

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <h1 class="visually-hidden">Навигация</h1>
Почему h1?

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +        <nav class="main-nav">
Иногда на сайтах есть навигация и в шапке и в футере. Поэтому один из вохможных вариантов разметки тут - это микс. main-nav + main-header__nav

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +    <header class="main-header">
Давай сократим блок до просто header. Так будет проще и легче

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <ul class="main-nav__list site-list">
А будем ли мы где то переиспользовать такой элемент как список с двумя пунктами? Я к тому что возможно site-list тут лишний класс и этот элемент скорее всего будет жить только в рамках родительского блока main-nav

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <ul class="main-nav__list user-list">
Аналогично комментарию выше

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +    <main class="main-index">
Скорее всего не понадобится этот класс, мы не стилизуем main

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +      <section class="main-index__description">
Чаще всего секция - блок. Это логично будет. intro, features, contacts и тд.

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +      <section class="main-index__interior interior">
Отказываемся от main-index__interior

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +      <section class="main-index__interior interior">
И кажется, что это все одна большая секция - description. Тут нет необходимости Предмет ыинтерьера и Детские игрушки делить на секции, т.к. это просто ссылки (по ТЗ)

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <p class="card-product__product-week">ТОВАР НЕДЕЛИ</p>
сcard-product__text может будет лучше?..

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <p class="card-product__product-week">ТОВАР НЕДЕЛИ</p>
и капс мы делаем через стили обычно

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +            <dt class="card-features__color card-text">Цвет:</dt>
card-text излишне

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <img class="card-product__images" src="img/card-product/knitted_baskets.png" width="260" height="315" alt="Вязаные корзинки.">
Давай добавим див-обертку. Так будет проще управлять при адаптиве

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <dl class="card-priсe">
Не тянет на блок. Это скорее элемент от card-product

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +      <section class="card-product">
Может просто products? старайся попроще давать имена классам и одним словом

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <button class="card-product__button" type="button">Заказать</button>
Кнопка - самый очевидный переиспольуемый элемент (как и заголовки кстати) давай сделаем тут микс - button products__button

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <ul class="about-list">
Наверно ты имел ввиду about__list? этот же список вряд ли можно будет вырвать отсюда и переиспользовать, он живет только в рамках секции about

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +                <div class="about-list__img"></div>
Не делаем пусые дивы для картинок, для этого есть пседоэлементы в css

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +            Я молодая мама, но всё равно<br>
Я думаю при адаптиве тебе сильно помешает br, обрежем шириной может?..

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +            Я молодая мама, но всё равно<br>
И для отзыва используй семантчиеский тег blockquote?

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +            <button class="prev" type="button">
reviews__button reviews__button--prev будет здесь лучше. С кнопкой ниже аналогично только модификатор будет уже --next

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +          <dl class="contacts-card">
contacts__card

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +            <dd class="contacts-card__email-data">info@mimimishkashop.ru</dd>
это ссылк с протоклом mailto

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +        <img class="contacts__map" src="img/contacts/map-mobile.png" width="320" height="455" alt="Как нас найти.">
обертку

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +        <div class="page__container">
Не уверен что это тут нужно

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +              <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy">Мы в Вконтакте</a>
noref noopener

2022-07-31 16:22 UTC, summertime-fms commented on source/index.html
> +              <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy">Мы в Вконтакте</a>
если я не рассказывал про эти атрибуты то погугли или напиши в тг мне

2022-07-31 16:30 UTC, ustyugovki commented on source/index.html
> +<html class="page" lang="ru">
Как понимаю, это для стики футера

2022-07-31 16:42 UTC, ustyugovki commented on source/index.html
> +      <div class="page__container">
Да, согласен. Затупил

2022-07-31 16:54 UTC, ustyugovki commented on source/index.html
> +          <h1 class="visually-hidden">Навигация</h1>
Наткнулся на старую спецификацию и там можно было h1. Написал, прогнал через валидатор/nu тот промолчал.
Но всё таки наверное H2, судя по мозиле

2022-07-31 16:57 UTC, ustyugovki commented on source/index.html
> +          <dl class="contacts-card">
Почему не блок? У элемента и блоков может быть разная вложенность

2022-07-31 17:02 UTC, ustyugovki commented on source/index.html
> +        <img class="contacts__map" src="img/contacts/map-mobile.png" width="320" height="455" alt="Как нас найти.">
оберткой выступает  сама секция <section class="contacts">
текст контактов и кнопка после карты центрируется оберткой page__container
а картинка, которая по середине располагается на всю ширину страницы

2022-07-31 17:02 UTC, ustyugovki commented on source/index.html
> +        <div class="page__container">
обертка для центрирования кнопки

2022-07-31 17:03 UTC, ustyugovki commented on source/index.html
> +              <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy">Мы в Вконтакте</a>
не рассказывал

2022-07-31 17:05 UTC, summertime-fms commented on source/index.html
> +<html class="page" lang="ru">
Ну а причем тут класс для html? Стики-футер это когда футер прибит к низу. Чтобы прибить его мы делаем body флексом или гридом (кому что нравится). Мы не трогаем при этом тег html. Но даже когда пилим сетку для body мы этот тег стилизуем не по классу а по тегу.

2022-07-31 17:06 UTC, summertime-fms commented on source/index.html
> +          <h1 class="visually-hidden">Навигация</h1>
Не может на странице быть несколько h1. Это грубое нарушение.

2022-07-31 17:06 UTC, summertime-fms commented on source/index.html
> +          <h1 class="visually-hidden">Навигация</h1>
https://yoksel.github.io/html-tree/ Вот тут тебе валидатор скажет то же самое.

2022-07-31 17:07 UTC, summertime-fms commented on source/index.html
> +          <dl class="contacts-card">
Потому что этот блок вряд ли можно вырвать и где то еще переиспользовать.

2022-07-31 17:10 UTC, summertime-fms commented on source/index.html
> +        <img class="contacts__map" src="img/contacts/map-mobile.png" width="320" height="455" alt="Как нас найти.">
Не обязательно для этого выносить картинку за пределы враппера. Ты можешь растянуть ее на всю ширину задав отрицательные марджины. (насильственное растягивание). Это хорошая практика.

2022-07-31 17:10 UTC, summertime-fms commented on source/index.html
> +        <div class="page__container">
картинку - внутрь враппера. Соответстенно весь контент секции будет внутри враппера и тут мы уберем этот див

2022-07-31 17:11 UTC, summertime-fms requested changes

2022-07-31 17:11 UTC, summertime-fms commented on source/index.html
> +        <img class="contacts__map" src="img/contacts/map-mobile.png" width="320" height="455" alt="Как нас найти.">
Но тут я имел ввиду обернуть картинку в див, т.к. мы будем управлять поведением изображений от обертки-дива.

2022-07-31 17:11 UTC, summertime-fms commented on source/index.html
> +              <a class="social__link social__link--vkontakte" href="https://vk.com/htmlacademy">Мы в Вконтакте</a>
https://cpa-rating.ru/stati/chto-takoe-rel--noreferrer-noopener-i-kak-etot-teg-vliyaet-na-seo

2022-07-31 17:14 UTC, ustyugovki commented on source/index.html
> +          <h1 class="visually-hidden">Навигация</h1>
Я это тоже проверял)))

![image](https://user-images.githubusercontent.com/95860927/182037656-75af1d90-0e52-4d70-9177-b86e9cb0bbdd.png)

но будет ли cемантично начинать с H2, потом H1, потом H2

2022-07-31 17:16 UTC, ustyugovki commented on source/index.html
> +          <ul class="main-nav__list user-list">
Да, согласен. Поэтому дальше в коде не стал городить классы, а просто разметил крупные блок

2022-07-31 17:27 UTC, ustyugovki commented on source/index.html
> +<html class="page" lang="ru">
Так в БЭМе запрещены теги

2022-07-31 17:33 UTC, ustyugovki commented on source/index.html
> +          <p class="card-product__product-week">ТОВАР НЕДЕЛИ</p>
А если появится описание или какой нибудь другой текст ?

Копипаст из фигмы)

2022-07-31 17:39 UTC, ustyugovki commented on source/index.html
> +          <ul class="about-list">
Ну это фичи, можно перенести в какие нибудь общие характеристики

2022-08-03 14:32 UTC, summertime-fms commented on source/catalog.html
> +        <h2 class="process__title">Процесс производства</h2>
Заголовки можно вынести в блок. title title--h2 process__title  например

2022-08-03 14:32 UTC, summertime-fms commented on source/catalog.html
> +        <button class="button process__button process__button--play" type="submit">Показать видео</button>
где отправляем форму?

2022-08-03 14:32 UTC, summertime-fms commented on source/catalog.html
> +        <button class="button process__button" type="submit">Сделать заказ</button>
Аналогично

2022-08-03 14:32 UTC, summertime-fms commented on source/catalog.html
> +        <div class="main-footer__social social">
Мне кажется это лишний див)

2022-08-04 12:49 UTC, merged